### ISSUE TITLE
Move away from plain html

### ISSUE THREAD

**Issue by ChillerDragon** [ChillerDragon/teeworlds-protocol#13]
As much as I love writing vanilla html the disadvantages outweigh the advantages for sure.
html is super error prone and I do not have any validator in place. Maybe use something that generates html instead of writing it directly.

Also not being able to use components causes a bunch of code replication.

The question now is just which tool to use. The transition process should work seamless as in not everything has to be ported at once.
And the tool should not be bloat slow or require maintenance.

Serving javascript or having a backend could be cool for a tools section.

Some easy and fast search with good hits would also be key already with the current content size. I am thinking of a ux like brew.sh ctrl+ which is so smooth!

**Comment by ChillerDragon** [comment]
Plan changed. Do not use any tooling. Tooling gets outdated html does not. This project should still work without maintenance in 10 years. Do not use any frameworks. Do not transpile or compile. Only lint.

There is the competing project https://github.com/teeframe/protocol-documentation now. Which is using vitepress. So just contribute there or use that if needed.

I will not solve any dependency issues in 5 years that will get messy inevitably no matter which tooling is used.

**Comment by jxsl13** [comment]
check out 'hugo' static html generator if the plan changes again :)
